name: Drone API Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with report
        run: |
          pytest --junitxml=results.xml --html=report.html --self-contained-html

      - name: Upload JUnit test report
        uses: actions/upload-test-report@v1
        with:
          path: results.xml

      - name: Upload HTML test report
        uses: actions/upload-artifact@v3
        with:
          name: html-test-report
          path: report.html
