name: API Test Pipeline

on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio pytest-html httpx uvicorn

      - name: Start FastAPI in background
        run: |
          nohup uvicorn app.app:app --host 127.0.0.1 --port 8000 --log-level warning &
          sleep 5

      - name: Run tests and generate HTML report
        run: |
          pytest --html=report.html

      - name: Upload report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: report.html
