name: API Test Pipeline

on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mock-api:
        image: tiangolo/uvicorn-gunicorn-fastapi:python3.9
        ports:
          - 8000:80
        env:
          MODULE_NAME: app.app
        options: >-
          --health-cmd "curl -f http://localhost:80/docs || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio pytest-html httpx

      - name: Wait for server to be ready
        run: sleep 10 # just to make sure it's live

      - name: Run tests and generate HTML report
        run: |
          pytest --html=report.html

      - name: Upload report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: report.html
